### ISSUE TITLE
Support custom fields

### ISSUE THREAD

**Issue by Oehmi** [sphereio/sphere-stock-export#17]
### Description
We'd like to support custom fields in the stock export in IMPEX. 

### Context
We recently introduced custom fields within the stock import, but they aren't included in the export. This is needed for one of our customers that will be doing changes to the data model for inventory, and needs to export all stock data beforehand, in order to import them afterwards again.

**Comment by hisabimbola** [comment]
Fixed in commercetools/nodejs#230
