### ISSUE TITLE
Add time parameter for fetching stocks

### ISSUE THREAD

**Issue by mmoelli** [sphereio/sphere-stock-export#2]

**Comment by junajan** [comment]
@mmoelli - I propose to add `--where` as it is done for example on [order-export](https://github.com/sphereio/sphere-order-export/blob/master/src/coffee/run.coffee#L37) module. With this we can specify our own predicate for filtering stocks..

**Comment by mmoelli** [comment]
@junajan Sounds great, from my point of view low priority.

**Comment by junajan** [comment]
After a quick look, I found out that there is already a `queryString` parameter so we can just add datetime pickers to impex which will use this param.

**Comment by junajan** [comment]
@mmoelli - there is one thing I am not sure about.. should we filter stocks by `createdAt` or `lastModifiedAt` date?

**Comment by mmoelli** [comment]
@junajan please use ```lastModifiedAt``` This is more relevant then when it was created.

**Comment by junajan** [comment]
When you use CLI version of this tool, you can use a `--queryString` parameter to filter exported stocks.

**Example usage:**
`stock-export --projectKey project-name --targetFile exported-stocks.csv --queryString 'lastModifiedAt >= "2016-11-18T19:00" AND lastModifiedAt <= "2017-01-22T19:00"'`

I created a PR which adds this functionality also in Impex.
